package com.db.mapper;

import com.db.entity.AppAddress;

public interface AppAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    int insert(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    int insertSelective(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    AppAddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AppAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appaddress
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AppAddress record);
}